name: Test

on:
  push:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        image:
          - name: python3.10
            python_version: "3.10"
          - name: python3.9
            python_version: "3.9"
          - name: python3.8
            python_version: "3.8"
          - name: python3.8-slim
            python_version: "3.8"
          - name: python3.9-slim
            python_version: "3.9"
          - name: python3.10-slim
            python_version: "3.10"
      fail-fast: true
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Dependencies
        run: python -m pip install "docker>=4.4.4,<5.0.0" "pytest>=6.2.4,<7.0.0"
      - name: Test Image
        run: bash scripts/test.sh
        env:
          NAME: ${{ matrix.image.name }}
          DOCKERFILE: ${{ matrix.image.dockerfile }}
          PYTHON_VERSION: ${{ matrix.image.python_version }}
